### ISSUE TITLE
CGMP doesn't disable scrolling healing or damage since updating to V10.

### ISSUE THREAD

**Issue by YourDNDPleasesMe** [cs96and/FoundryVTT-CGMP#16]
Updated today and noticed the scrolling healing that I usually have disabled was visible. I've tried uninstalling and reinstalling and updating all modules. 

Still happens when I only have CGMP and libwrapper activated. I recorded an example with all of my FVTT and module versions visible in the video. 
https://user-images.githubusercontent.com/87000878/196097059-ab8aad46-5355-4e05-b63c-5d3c4c3ac273.mp4

**Comment by cs96and** [comment]
77805a001ef19b057eabffe13834dc4c051696b4

**Comment by cs96and** [comment]
Fixed in v0.9.1

**Comment by YourDNDPleasesMe** [comment]
Thanks, this seems to be working now. 

A question though - I still see the healing on the DM screen. Is this a change from how it worked in V9? I thought I remembered it hiding it for both GM and Players, but now it only hides it for players. 

https://user-images.githubusercontent.com/87000878/197687482-62ce0d6d-83e5-4f68-93b2-5efbb64c7c90.mp4
